
server:
  ignore_compose_stack_name_keywords:
    - devcontainer
  possible_homepage_labels:  # order matters!
    - org.label-schema.url
    - org.opencontainers.image.url
    - org.opencontainers.image.source
  possible_image_version_labels:  # order matters!
    - org.label-schema.version
    - org.opencontainers.image.version

auto_updater:
  enabled: false
  interval: 1d
  max_concurrent: 1
