
services:
  vsc-docking-station:
    build:
      context: ".."
      dockerfile: .devcontainer/Dockerfile
    container_name: vsc-docking-station
    env_file: .env
    volumes:
      - docking-station-config:/config
      - vsc-docking-station-vscode-server:/root/.vscode-server
      - ..:/workspaces/docking-station:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /mnt/big-vault/appdata/compose:/mnt/big-vault/appdata/compose
    labels:
      # for homepage dashboard widget. More info: https://gethomepage.dev/latest/configs/docker/#automatic-service-discovery
      - homepage.group=Dev Containers
      - homepage.name=vsc-docking-station
      - homepage.icon=code
      - homepage.href=http://localhost:3000
    command: sleep infinity
    # entrypoint: "/workspaces/docking-station/entrypoint.sh"

volumes:
  vsc-docking-station-vscode-server:
  docking-station-config:
