name: Publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# on:
#   release:
#     types: [ published ]

jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4

    - name: Login to Docking Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: docker compose -f docker-compose.deploy.yaml build --push
